### ISSUE TITLE
Archiving G_String

### ISSUE THREAD

**Issue by Papa-26** [G-String-Legacy/G_String#6]
Originally I created a separate repository to keep an archival version of the various major software versions, as well as a separate repository for active work on the software. But Bas Peters recommended that I only have one repository. So I incorporated the workbench and archive within G_String. That worked fine, as far as workbench was concerned. But when I tried to set a branch of archive into archival state, the whole repository went into archival and became useless as an active git repository.
After reading GitHub's persistence policy, I decide to keep offline source code archives and removed the archive from G_String.

**Comment by nominalie** [comment]
Bas said to have only one repo? I would have thought perhaps you could have archived the original source repo and then create a fork from it in order to create your new working repo (or workbench repo, per your preferred terminology).
